### ISSUE TITLE
import ENTRY_COMPONENTS

### ISSUE THREAD

**Issue by cesaraltame** [giscafer/primeng-ext#2]

**Comment by giscafer** [comment]
`EntryComponents.ts` just a list of components which uses to dynamic render.

```ts
export const ENTRY_COMPONENTS =[
   TestComponent,
   DemoComponent
];

```

This component is used in the old project, but the new projects are all using [resue-tab](https://github.com/ng-alain/delon/blob/master/packages/abc/reuse-tab/index.en-US.md) 

suggest you to using [resue-tab](https://github.com/ng-alain/delon/blob/master/packages/abc/reuse-tab/index.en-US.md) instead of this component
